window.MG_BOATS = {
 "marlin182": {
  "id": "marlin182",
  "name": "Marlin 182",
  "kind": "louer",
  "cat": "semi",
  "color": "Vert d'eau",
  "length": 5.55,
  "cap": 6,
  "power": "115 CV",
  "engine": "Suzuki",
  "price": 290,
  "sold": false,
  "tag": "",
  "blurb": "Le plus maniable de la flotte : idéal pour une escapade à la journée dans les calanques.",
  "gallery": [
   "assets/images/boats/marlin182/00.jpg",
   "assets/images/boats/marlin182/01.jpg",
   "assets/images/boats/marlin182/02.jpg",
   "assets/images/boats/marlin182/03.jpg",
   "assets/images/boats/marlin182/04.jpg"
  ],
  "seasons": {
   "basse": 260,
   "moyenne": 290,
   "haute": 320
  },
  "fuel": "140L",
  "equip": [
   "Douchette eau claire",
   "Échelle de bain",
   "GPS/sondeur",
   "Plancher en mousse reflex",
   "Poste radio (BT)",
   "Prise USB/12V",
   "Taud de soleil"
  ],
  "options": [
   "Bouée 1 place 30 €",
   "Bouée 2 places 50 €",
   "Ski nautiques 50 €",
   "Wakeboard 50 €",
   "Torpille sous-marine 80 €"
  ]
 },
 "asso62": {
  "id": "asso62",
  "name": "Asso 62",
  "kind": "louer",
  "cat": "semi",
  "color": "Coque noire",
  "length": 6.2,
  "cap": 10,
  "power": "150 CV",
  "engine": "",
  "price": 405,
  "sold": false,
  "tag": "",
  "blurb": "Un semi-rigide sobre et sûr, parfait pour la famille et les criques de Bonifacio.",
  "gallery": [
   "assets/images/boats/asso62/00.jpg",
   "assets/images/boats/asso62/01.jpg",
   "assets/images/boats/asso62/02.jpg",
   "assets/images/boats/asso62/03.jpg",
   "assets/images/boats/asso62/04.jpg"
  ],
  "seasons": {
   "basse": 360,
   "moyenne": 405,
   "haute": 450
  },
  "fuel": "200L",
  "equip": [
   "Douchette eau claire",
   "Échelle de bain",
   "GPS/sondeur",
   "Poste radio (BT/AUX)",
   "Prise USB/12V",
   "Taud de soleil"
  ],
  "options": [
   "Bouée 1 place 30 €",
   "Bouée 2 places 50 €",
   "Ski nautiques 50 €",
   "Wakeboard 50 €",
   "Torpille sous-marine 80 €"
  ]
 },
 "capelli626": {
  "id": "capelli626",
  "name": "Capelli 626",
  "kind": "louer",
  "cat": "semi",
  "color": "Orange",
  "length": 6.26,
  "cap": 10,
  "power": "150 CV",
  "engine": "",
  "price": 360,
  "sold": false,
  "tag": "",
  "blurb": "Compact et convivial, le Capelli 626 file vers les plages des Cerbicale.",
  "gallery": [
   "assets/images/boats/capelli626/00.jpg",
   "assets/images/boats/capelli626/01.jpg",
   "assets/images/boats/capelli626/02.jpg",
   "assets/images/boats/capelli626/03.jpg",
   "assets/images/boats/capelli626/04.jpg"
  ],
  "seasons": {
   "basse": 320,
   "moyenne": 360,
   "haute": 400
  },
  "fuel": "150L",
  "equip": [
   "Douchette eau claire",
   "Échelle de bain",
   "GPS/sondeur",
   "Poste radio (BT)",
   "Prise USB/12V",
   "Taud de soleil"
  ],
  "options": [
   "Bouée 1 place 30 €",
   "Bouée 2 places 50 €",
   "Ski nautiques 50 €",
   "Wakeboard 50 €",
   "Torpille sous-marine 80 €"
  ]
 },
 "marlin226": {
  "id": "marlin226",
  "name": "Marlin 226",
  "kind": "louer",
  "cat": "semi",
  "color": "Rouge",
  "length": 6.9,
  "cap": 10,
  "power": "175 CV",
  "engine": "",
  "price": 450,
  "sold": false,
  "tag": "",
  "blurb": "Le juste équilibre entre confort et performance pour explorer le golfe.",
  "gallery": [
   "assets/images/boats/marlin226/00.jpg",
   "assets/images/boats/marlin226/01.jpg",
   "assets/images/boats/marlin226/02.jpg",
   "assets/images/boats/marlin226/03.jpg",
   "assets/images/boats/marlin226/04.jpg"
  ],
  "seasons": {
   "basse": 400,
   "moyenne": 450,
   "haute": 500
  },
  "fuel": "200L",
  "equip": [
   "Douchette eau claire",
   "Échelle de bain",
   "GPS/sondeur",
   "Plateformes de bain en teck",
   "Poste radio (BT)",
   "Prise USB/12V",
   "Table amovible",
   "Taud de soleil"
  ],
  "options": [
   "Skipper 250 €",
   "Bouée 1 place 30 €",
   "Bouée 2 places 50 €",
   "Ski nautiques 50 €",
   "Wakeboard 50 €",
   "Torpille sous-marine 80 €"
  ]
 },
 "marlin24sr": {
  "id": "marlin24sr",
  "name": "Marlin 24 SR – Refit 2025",
  "kind": "louer",
  "cat": "semi",
  "color": "Sellerie cognac",
  "length": 7.4,
  "cap": 12,
  "power": "250 CV",
  "engine": "Suzuki",
  "price": 585,
  "sold": false,
  "tag": "Refit 2025",
  "blurb": "Refait à neuf par nos ateliers en 2025 — teck massif et sellerie cognac.",
  "gallery": [
   "assets/images/boats/marlin24sr/00.jpg",
   "assets/images/boats/marlin24sr/01.jpg",
   "assets/images/boats/marlin24sr/02.jpg",
   "assets/images/boats/marlin24sr/03.jpg",
   "assets/images/boats/marlin24sr/04.jpg"
  ],
  "seasons": {
   "basse": 520,
   "moyenne": 585,
   "haute": 650
  },
  "fuel": "220L",
  "equip": [
   "Douchette eau claire",
   "Échelle de bain",
   "GPS/sondeur",
   "Guindeau électrique",
   "Plancher en mousse reflex",
   "Poste radio (BT/AUX)",
   "Prise USB/12V",
   "Réfrigérateur",
   "Table amovible",
   "Taud de soleil"
  ],
  "options": [
   "Skipper 250 €",
   "Bouée 1 place 30 €",
   "Bouée 2 places 50 €",
   "Ski nautiques 50 €",
   "Wakeboard 50 €",
   "Torpille sous-marine 80 €"
  ]
 },
 "marlin24sr2023": {
  "id": "marlin24sr2023",
  "name": "Marlin 24 SR – 2023",
  "kind": "louer",
  "cat": "semi",
  "color": "Sellerie cognac",
  "length": 7.4,
  "cap": 12,
  "power": "250 CV",
  "engine": "Suzuki",
  "price": 585,
  "sold": false,
  "tag": "2023",
  "blurb": "Le millésime 2023 du 24 SR, nerveux et élégant, jusqu'à 12 invités.",
  "gallery": [
   "assets/images/boats/marlin24sr2023/00.jpg",
   "assets/images/boats/marlin24sr2023/01.jpg",
   "assets/images/boats/marlin24sr2023/02.jpg",
   "assets/images/boats/marlin24sr2023/03.jpg",
   "assets/images/boats/marlin24sr2023/04.jpg"
  ],
  "seasons": {
   "basse": 520,
   "moyenne": 585,
   "haute": 650
  },
  "fuel": "220L",
  "equip": [
   "Douchette eau claire",
   "Échelle de bain",
   "GPS/sondeur",
   "Guindeau électrique",
   "Plancher en mousse reflex",
   "Poste radio (BT/AUX)",
   "Prise USB/12V",
   "Réfrigérateur",
   "Table amovible",
   "Taud de soleil"
  ],
  "options": [
   "Skipper 250 €",
   "Bouée 1 place 30 €",
   "Bouée 2 places 50 €",
   "Ski nautiques 50 €",
   "Wakeboard 50 €",
   "Torpille sous-marine 80 €"
  ]
 },
 "bsc78": {
  "id": "bsc78",
  "name": "BSC 78",
  "kind": "louer",
  "cat": "semi",
  "color": "Sable",
  "length": 7.9,
  "cap": 12,
  "power": "300 CV",
  "engine": "",
  "price": 630,
  "sold": false,
  "tag": "",
  "blurb": "Ligne italienne et grand cockpit teck pour des journées en mer haut de gamme.",
  "gallery": [
   "assets/images/boats/bsc78/00.jpg",
   "assets/images/boats/bsc78/01.jpg",
   "assets/images/boats/bsc78/02.jpg",
   "assets/images/boats/bsc78/03.jpg"
  ],
  "seasons": {
   "basse": 560,
   "moyenne": 630,
   "haute": 700
  },
  "fuel": "310L",
  "equip": [
   "Carré extérieur",
   "Douchette eau claire",
   "Échelle de bain",
   "GPS/sondeur",
   "Guindeau électrique",
   "Plancher en mousse reflex",
   "Poste radio (BT/AUX)",
   "Prise USB/12V",
   "Réfrigérateur",
   "Table amovible"
  ],
  "options": [
   "Skipper 250 €",
   "Bouée 1 place 30 €",
   "Bouée 2 places 50 €",
   "Ski nautiques 50 €",
   "Wakeboard 50 €",
   "Torpille sous-marine 80 €"
  ]
 },
 "marlin274": {
  "id": "marlin274",
  "name": "Marlin 274 – Refit 2024",
  "kind": "louer",
  "cat": "semi",
  "color": "Vert olive",
  "length": 8.35,
  "cap": 12,
  "power": "350 CV",
  "engine": "Suzuki",
  "price": 675,
  "sold": false,
  "tag": "Refit 2024",
  "blurb": "Notre best-seller, refait à neuf en 2024 : sellerie vert olive et pont teck.",
  "gallery": [
   "assets/images/boats/marlin274/00.jpg",
   "assets/images/boats/marlin274/01.jpg",
   "assets/images/boats/marlin274/02.jpg",
   "assets/images/boats/marlin274/03.jpg",
   "assets/images/boats/marlin274/04.jpg"
  ],
  "seasons": {
   "basse": 600,
   "moyenne": 675,
   "haute": 750
  },
  "fuel": "300L",
  "equip": [
   "Cabine salle d'eau avec WC",
   "Douchette eau claire",
   "Échelle de bain",
   "GPS/sondeur",
   "Guindeau électrique",
   "Plancher et plateformes de bain en teck massif",
   "Poste radio (BT/AUX)",
   "Prise USB/12V",
   "Réfrigérateur",
   "Table amovible",
   "Taud de soleil"
  ],
  "options": [
   "Skipper 250 €",
   "Bouée 1 place 30 €",
   "Bouée 2 places 50 €",
   "Ski nautiques 50 €",
   "Wakeboard 50 €",
   "Torpille sous-marine 80 €"
  ]
 },
 "marlin298": {
  "id": "marlin298",
  "name": "Marlin 298",
  "kind": "louer",
  "cat": "semi",
  "color": "Bleu",
  "length": 9.15,
  "cap": 12,
  "power": "400 CV",
  "engine": "Suzuki",
  "price": 810,
  "sold": false,
  "tag": "",
  "blurb": "Le grand semi-rigide bleu : bain de soleil XXL et cabine pour la journée parfaite.",
  "gallery": [
   "assets/images/boats/marlin298/00.jpg",
   "assets/images/boats/marlin298/01.jpg",
   "assets/images/boats/marlin298/02.jpg",
   "assets/images/boats/marlin298/03.jpg",
   "assets/images/boats/marlin298/04.jpg"
  ],
  "seasons": {
   "basse": 720,
   "moyenne": 810,
   "haute": 900
  },
  "fuel": "440L",
  "equip": [
   "Cabine salle d'eau",
   "Douchette eau claire",
   "Échelle de bain",
   "GPS/sondeur",
   "Guindeau électrique",
   "Plancher et plateformes de bain en teck massif",
   "Poste radio (BT/AUX)",
   "Prise USB/12V",
   "Réfrigérateur",
   "Table amovible",
   "Taud de soleil"
  ],
  "options": [
   "Skipper 250 €",
   "Bouée 1 place 30 €",
   "Bouée 2 places 50 €",
   "Ski nautiques 50 €",
   "Wakeboard 50 €",
   "Torpille sous-marine 80 €"
  ]
 },
 "capelli900": {
  "id": "capelli900",
  "name": "Capelli 900 WA",
  "kind": "louer",
  "cat": "semi",
  "color": "Bleu marine",
  "length": 9.3,
  "cap": 12,
  "power": "500 CV",
  "engine": "",
  "price": 810,
  "sold": false,
  "tag": "",
  "blurb": "Un walkaround généreux, pensé pour la baignade et les longues navigations.",
  "gallery": [
   "assets/images/boats/capelli900/00.jpg",
   "assets/images/boats/capelli900/01.jpg",
   "assets/images/boats/capelli900/02.jpg",
   "assets/images/boats/capelli900/03.jpg",
   "assets/images/boats/capelli900/04.jpg"
  ],
  "seasons": {
   "basse": 720,
   "moyenne": 810,
   "haute": 900
  },
  "fuel": "400L",
  "equip": [
   "Cabine salle d'eau avec WC",
   "Carré extérieur",
   "Douchette eau claire",
   "Échelle de bain",
   "GPS/sondeur",
   "Guindeau électrique",
   "Plancher et plateformes de bain en teck massif",
   "Poste radio (BT)",
   "Prise 12V",
   "Réfrigérateur",
   "T-Top",
   "Table amovible"
  ],
  "options": [
   "Skipper 250 €",
   "Torpille sous-marine 80 €"
  ]
 },
 "capelli1000sun": {
  "id": "capelli1000sun",
  "name": "Capelli 1000 SUN",
  "kind": "louer",
  "cat": "semi",
  "color": "Bleu",
  "length": 10.0,
  "cap": 12,
  "power": "500 CV",
  "engine": "",
  "price": 900,
  "sold": false,
  "tag": "",
  "blurb": "Dix mètres de pur plaisir : le Capelli 1000 Sun et son immense plage avant.",
  "gallery": [
   "assets/images/boats/capelli1000sun/00.jpg",
   "assets/images/boats/capelli1000sun/01.jpg",
   "assets/images/boats/capelli1000sun/02.jpg",
   "assets/images/boats/capelli1000sun/03.jpg",
   "assets/images/boats/capelli1000sun/04.jpg"
  ],
  "seasons": {
   "basse": 780,
   "moyenne": 900,
   "haute": 1000
  },
  "fuel": "410L",
  "equip": [
   "Cabine",
   "Cabine salle d'eau avec WC",
   "Carré extérieur",
   "Douchette eau claire",
   "Échelle de bain",
   "GPS/sondeur",
   "Guindeau électrique",
   "Plancher et plateformes de bain en teck massif",
   "Poste radio (BT)",
   "Prise USB/12V",
   "Réfrigérateur",
   "Table amovible",
   "Taud de soleil"
  ],
  "options": [
   "Torpille sous-marine 80 €"
  ]
 },
 "capelli1000wa": {
  "id": "capelli1000wa",
  "name": "Capelli 1000 WA",
  "kind": "louer",
  "cat": "semi",
  "color": "Bleu",
  "length": 10.0,
  "cap": 12,
  "power": "500 CV",
  "engine": "",
  "price": 900,
  "sold": false,
  "tag": "",
  "blurb": "La version walkaround du 1000 : circulation à bord et cabine confortable.",
  "gallery": [
   "assets/images/boats/capelli1000wa/00.jpg",
   "assets/images/boats/capelli1000wa/01.jpg",
   "assets/images/boats/capelli1000wa/02.jpg"
  ],
  "seasons": {
   "basse": 780,
   "moyenne": 900,
   "haute": 1000
  },
  "fuel": "440L",
  "equip": [
   "Cabine",
   "Cabine salle d'eau avec WC",
   "Carré extérieur",
   "Douchette eau claire",
   "Échelle de bain",
   "GPS/sondeur",
   "Guindeau électrique",
   "Plateformes de bain en teck",
   "Poste radio (BT/AUX)",
   "Prise USB/12V",
   "Réfrigérateur",
   "Table amovible",
   "Taud de soleil"
  ],
  "options": [
   "Paddle 70 €",
   "Torpille sous-marine 80 €"
  ]
 },
 "marlin38": {
  "id": "marlin38",
  "name": "Marlin 38 – Refit 2024",
  "kind": "louer",
  "cat": "semi",
  "color": "Teck",
  "length": 12.0,
  "cap": 12,
  "power": "700 CV",
  "engine": "",
  "price": 1080,
  "sold": false,
  "tag": "Refit 2024",
  "blurb": "Le vaisseau amiral des semi-rigides : 12 mètres, trois moteurs, teck massif.",
  "gallery": [
   "assets/images/boats/marlin38/00.jpg",
   "assets/images/boats/marlin38/01.jpg",
   "assets/images/boats/marlin38/02.jpg",
   "assets/images/boats/marlin38/03.jpg",
   "assets/images/boats/marlin38/04.jpg"
  ],
  "seasons": {
   "basse": 960,
   "moyenne": 1080,
   "haute": 1200
  },
  "fuel": "700L",
  "equip": [
   "Cabine double",
   "Cabine salle d'eau avec WC",
   "Double taud de soleil",
   "Douchette eau claire",
   "Échelle de bain",
   "GPS/sondeur",
   "Guindeau électrique",
   "Plancher et plateformes de bain en teck massif",
   "Poste radio (BT/AUX)",
   "Prise USB/12V",
   "Réfrigérateur",
   "Table amovible"
  ],
  "options": [
   "Skipper obligatoire 300€",
   "Paddle 70 €",
   "Torpille sous-marine 80 €"
  ]
 },
 "flyer66": {
  "id": "flyer66",
  "name": "Beneteau Flyer 6.6",
  "kind": "louer",
  "cat": "day",
  "color": "Gris",
  "length": 6.6,
  "cap": 6,
  "power": "200 CV",
  "engine": "",
  "price": 405,
  "sold": false,
  "tag": "",
  "blurb": "Un day-cruiser léger et frais pour une première journée en mer réussie.",
  "gallery": [
   "assets/images/boats/flyer66/00.jpg",
   "assets/images/boats/flyer66/01.jpg",
   "assets/images/boats/flyer66/02.jpg",
   "assets/images/boats/flyer66/03.jpg",
   "assets/images/boats/flyer66/04.jpg"
  ],
  "seasons": {
   "basse": 360,
   "moyenne": 405,
   "haute": 450
  },
  "equip": [
   "Barre de wakeboard",
   "Cabine",
   "Douchette eau claire",
   "Échelle de bain",
   "GPS/sondeur",
   "Poste radio (BT/AUX)",
   "Prise USB/12V",
   "T-Top",
   "Table amovible"
  ],
  "options": [
   "Skipper 250 €",
   "Bouée 1 place 30 €",
   "Bouée 2 places 50 €",
   "Ski nautiques 50 €",
   "Wakeboard 50 €",
   "Torpille sous-marine 80 €"
  ]
 },
 "protagon25": {
  "id": "protagon25",
  "name": "Protagon 25",
  "kind": "louer",
  "cat": "day",
  "color": "Teck",
  "length": 8.0,
  "cap": 12,
  "power": "250 CV",
  "engine": "",
  "price": 675,
  "sold": false,
  "tag": "2024",
  "blurb": "Center console élégant, tout en teck — la promenade chic dans le golfe.",
  "gallery": [
   "assets/images/boats/protagon25/00.jpg",
   "assets/images/boats/protagon25/01.jpg",
   "assets/images/boats/protagon25/02.jpg",
   "assets/images/boats/protagon25/03.jpg",
   "assets/images/boats/protagon25/04.jpg"
  ],
  "seasons": {
   "basse": 600,
   "moyenne": 675,
   "haute": 750
  },
  "fuel": "300L",
  "equip": [
   "Cabine salle d'eau avec WC",
   "Double taud de soleil",
   "Douchette eau claire",
   "Échelle de bain",
   "GPS/sondeur",
   "Guindeau électrique",
   "Kitchenette",
   "Plancher en mousse reflex",
   "Poste radio (BT)",
   "Prise USB/12V",
   "Réfrigérateur",
   "T-Top",
   "Table amovible"
  ],
  "options": [
   "Skipper 250 €",
   "Bouée 1 place 30 €",
   "Bouée 2 places 50 €",
   "Ski nautiques 50 €",
   "Wakeboard 50 €",
   "Torpille sous-marine 80 €"
  ]
 },
 "axopar29": {
  "id": "axopar29",
  "name": "Axopar 29 Sun Top",
  "kind": "louer",
  "cat": "day",
  "color": "Blanc",
  "length": 9.4,
  "cap": 9,
  "power": "400 CV",
  "engine": "",
  "price": 950,
  "sold": false,
  "tag": "",
  "blurb": "L'esprit scandinave : lignes tendues, sun-top et sensations de navigation.",
  "gallery": [
   "assets/images/boats/axopar29/00.jpg",
   "assets/images/boats/axopar29/01.jpg",
   "assets/images/boats/axopar29/02.jpg",
   "assets/images/boats/axopar29/03.jpg",
   "assets/images/boats/axopar29/04.jpg"
  ],
  "fuel": "400L",
  "equip": [
   "Barre de wakeboard",
   "Cabine",
   "Cabine salle d'eau avec WC",
   "Carré extérieur",
   "Double échelle de bain",
   "Douchette eau claire",
   "GPS/sondeur",
   "Guindeau électrique",
   "Plancher en mousse reflex",
   "Poste radio (BT)",
   "Réfrigérateur",
   "Sondeur",
   "T-Top",
   "Table amovible"
  ],
  "options": [
   "Skipper obligatoire 250€",
   "Bouée 1 place 30 €",
   "Bouée 2 places 50 €",
   "Ski nautiques 50 €",
   "Wakeboard 50 €",
   "Torpille sous-marine 80 €"
  ]
 },
 "fjord44": {
  "id": "fjord44",
  "name": "Fjord 44 Open",
  "kind": "louer",
  "cat": "vedette",
  "color": "Blanc",
  "length": 12.5,
  "cap": 8,
  "power": "900 CV",
  "engine": "",
  "price": 2500,
  "sold": false,
  "tag": "",
  "blurb": "Une vedette open spectaculaire : ponts vastes, design radical, luxe absolu.",
  "gallery": [
   "assets/images/boats/fjord44/00.jpg",
   "assets/images/boats/fjord44/01.jpg",
   "assets/images/boats/fjord44/02.jpg",
   "assets/images/boats/fjord44/03.jpg",
   "assets/images/boats/fjord44/04.jpg"
  ],
  "fuel": "1000L",
  "equip": [
   "Carré extérieur",
   "Douchette eau chaude & froide",
   "Échelle de bain",
   "GPS/sondeur",
   "Guindeau électrique",
   "Paddle",
   "Plancher et plateformes de bain en teck massif",
   "Poste radio (BT/AUX)",
   "Réfrigérateur",
   "Sondeur",
   "T-Top",
   "Table amovible",
   "Cabine master avec sa salle de bain",
   "Cabine twin",
   "Carré extérieur",
   "Kitchenette extérieure"
  ],
  "options": [
   "Skipper obligatoire 300€",
   "Torpille sous-marine 80 €"
  ]
 },
 "princessv58": {
  "id": "princessv58",
  "name": "Princess V58 HT",
  "kind": "louer",
  "cat": "yacht",
  "color": "Coque marine",
  "length": 18.5,
  "cap": 10,
  "power": "2 x 800 CV",
  "engine": "",
  "price": 3350,
  "sold": false,
  "tag": "",
  "blurb": "Un yacht sportif britannique de 18 m, cabines et flybridge, équipage sur demande.",
  "gallery": [
   "assets/images/boats/princessv58/00.jpg",
   "assets/images/boats/princessv58/01.jpg",
   "assets/images/boats/princessv58/02.jpg",
   "assets/images/boats/princessv58/03.jpg",
   "assets/images/boats/princessv58/04.jpg"
  ],
  "fuel": "2200L",
  "equip": [
   "Bouilloire",
   "Carré extérieur",
   "Douchette eau chaude & froide",
   "Échelle de bain",
   "Machine à café",
   "Paddle",
   "Poste radio (BT/AUX)",
   "Prise USB/12V",
   "Réfrigérateur",
   "Table amovible",
   "Taud de soleil",
   "Cabine double avec sa salle de bain",
   "Cabine master avec sa salle de bain",
   "Cabine twin avec sa salle de bain",
   "Carré extérieur",
   "Carré intérieur avec cuisine équipée et salle à manger",
   "Kitchenette extérieure"
  ],
  "options": [
   "Torpille sous-marine 80 €",
   "Équipage inclus"
  ]
 },
 "princess61": {
  "id": "princess61",
  "name": "Princess 61 Fly",
  "kind": "louer",
  "cat": "yacht",
  "color": "Coque grise",
  "length": 19.0,
  "cap": 12,
  "power": "2 x 800 CV",
  "engine": "",
  "price": 3550,
  "sold": false,
  "tag": "",
  "blurb": "Le flybridge Princess 61 : croisière grand luxe pour douze invités.",
  "gallery": [
   "assets/images/boats/princess61/00.jpg",
   "assets/images/boats/princess61/01.jpg",
   "assets/images/boats/princess61/02.jpg",
   "assets/images/boats/princess61/03.jpg",
   "assets/images/boats/princess61/04.jpg"
  ],
  "fuel": "2500L",
  "equip": [
   "Douchette eau chaude & froide",
   "Échelle de bain",
   "Machine à café",
   "Paddle",
   "Plancher et plateformes de bain en teck massif",
   "Poste radio (BT/AUX)",
   "Réfrigérateur",
   "Cabine double avec sa salle de bain",
   "Cabine master avec sa salle de bain",
   "Carré extérieur",
   "Carré intérieur avec cuisine équipée et salle à manger",
   "Fly bridge",
   "Kitchenette extérieure",
   "Salle de bain avec wc"
  ],
  "options": [
   "Torpille sous-marine 80 €",
   "Équipage inclus"
  ]
 },
 "mangusta80": {
  "id": "mangusta80",
  "name": "Mangusta 80",
  "kind": "louer",
  "cat": "yacht",
  "color": "Blanc",
  "length": 24.0,
  "cap": 10,
  "power": "2 x 750 CV",
  "engine": "Volvo Penta",
  "price": 5940,
  "sold": false,
  "tag": "Équipage inclus",
  "blurb": "24 mètres d'exception signés Mangusta, équipage inclus. La quintessence.",
  "gallery": [
   "assets/images/boats/mangusta80/00.jpg",
   "assets/images/boats/mangusta80/01.jpg",
   "assets/images/boats/mangusta80/02.jpg",
   "assets/images/boats/mangusta80/03.jpg"
  ],
  "seasons": {
   "basse": 5280,
   "moyenne": 5940,
   "haute": 6600
  },
  "equip": [
   "Bouilloire",
   "Douchette eau chaude & froide",
   "Échelle de bain",
   "Machine à café",
   "Paddle",
   "Poste radio (BT/AUX)",
   "Prise USB/12V",
   "Réfrigérateur",
   "Taud de soleil",
   "Cabine double avec sa salle de bain",
   "Cabine master avec sa salle de bain",
   "Cabine twin avec sa salle de bain",
   "Carré extérieur",
   "Carré intérieur avec cuisine équipée et salle à manger"
  ],
  "options": [
   "Torpille sous-marine 80 €",
   "Équipage inclus"
  ]
 },
 "s_marlin24sr": {
  "id": "s_marlin24sr",
  "name": "Marlin 24SR",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 7.3,
  "cap": null,
  "power": "300 CV",
  "engine": "Suzuki",
  "price": 110093,
  "sold": false,
  "tag": "",
  "blurb": "Le semi-rigide compact de la gamme Marlin, motorisable jusqu'à 300 CV.",
  "gallery": [
   "assets/images/boats/s_marlin24sr/00.jpg",
   "assets/images/boats/s_marlin24sr/01.jpg",
   "assets/images/boats/s_marlin24sr/02.jpg",
   "assets/images/boats/s_marlin24sr/03.jpg",
   "assets/images/boats/s_marlin24sr/04.jpg"
  ],
  "specsheet": {
   "Longueur": "7m30",
   "Largeur": "2m98",
   "Poids": "1 050 Kg",
   "Puissance max": "300",
   "Capacité": "14 Pax",
   "Carburant": "220 Lt",
   "Eau": "40 Lt"
  },
  "equip": [
   "4 anneaux de levage",
   "Bâche de transport et d'abri",
   "Console avec parebrise, main courante, instruments, direction et siège avant",
   "Couverture plages de bain et côtés en mousse Reflex",
   "Câblage, panneau d'utilité, klaxon, pompe de cale",
   "Direction hydraulique",
   "Douche électrique avec réservoir",
   "Feux de mat 360° à LED",
   "Gonfleur électrique avec manomètre",
   "Kit réparation",
   "Plateforme arrière avec échelle inox",
   "Réservoir d'essence inox",
   "Série complète de coussins pour sièges, dossiers et coffre avant",
   "Taquet inox"
  ]
 },
 "s_marlin274": {
  "id": "s_marlin274",
  "name": "Marlin 274",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 8.35,
  "cap": null,
  "power": "350 CV",
  "engine": "Suzuki",
  "price": 118496,
  "sold": false,
  "tag": "",
  "blurb": "Le best-seller Marlin, disponible neuf et personnalisable à volonté.",
  "gallery": [
   "assets/images/boats/s_marlin274/00.jpg",
   "assets/images/boats/s_marlin274/01.jpg",
   "assets/images/boats/s_marlin274/02.jpg",
   "assets/images/boats/s_marlin274/03.jpg",
   "assets/images/boats/s_marlin274/04.jpg"
  ],
  "specsheet": {
   "Longueur": "8m35",
   "Largeur": "2m92",
   "Poids": "1 400 Kg",
   "Puissance max": "1x350 / 2x200",
   "Capacité": "12 Pax",
   "Carburant": "300 Lt",
   "Eau": "80 Lt"
  },
  "equip": [
   "4 anneaux de levage",
   "Bâche de transport et d'abri",
   "Console avec parebrise, main courante, instruments, direction et siège avant",
   "Couverture plages de bain et côtés en mousse Reflex",
   "Câblage, panneau d'utilité, klaxon, pompe de cale",
   "Direction hydraulique",
   "Douche électrique avec réservoir",
   "Feux de mat 360° à LED",
   "Gonfleur électrique avec manomètre",
   "Guindeau avec chaine et ancre",
   "Kit réparation",
   "Plateforme arrière avec échelle inox",
   "Réservoir d'essence inox",
   "Série complète de coussins pour sièges, dossiers et coffre avant",
   "Taquet inox"
  ]
 },
 "s_marlin298": {
  "id": "s_marlin298",
  "name": "Marlin 298",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 9.15,
  "cap": null,
  "power": "450 CV",
  "engine": "Suzuki",
  "price": 139244,
  "sold": false,
  "tag": "",
  "blurb": "Grand semi-rigide de croisière, jusqu'à 450 CV et cabine confortable.",
  "gallery": [
   "assets/images/boats/s_marlin298/00.jpg",
   "assets/images/boats/s_marlin298/01.jpg",
   "assets/images/boats/s_marlin298/02.jpg",
   "assets/images/boats/s_marlin298/03.jpg",
   "assets/images/boats/s_marlin298/04.jpg"
  ],
  "specsheet": {
   "Longueur": "9m15",
   "Largeur": "2m95",
   "Poids": "1 520 Kg",
   "Puissance max": "1x450 / 2x250",
   "Capacité": "16 Pax",
   "Carburant": "440 Lt",
   "Eau": "80 Lt"
  },
  "equip": [
   "4 anneaux de levage",
   "Bâche de transport et d'abri",
   "Console avec parebrise, main courante, instruments, direction et siège avant",
   "Couverture plages de bain et côtés en mousse Reflex",
   "Câblage, panneau d'utilité, klaxon, pompe de cale",
   "Direction hydraulique",
   "Douche électrique avec réservoir",
   "Feux de mat 360° à LED",
   "Gonfleur électrique avec manomètre",
   "Guindeau avec chaine et ancre",
   "Kit réparation",
   "Plateforme arrière avec échelle inox",
   "Réservoir d'essence inox",
   "Série complète de coussins pour sièges, dossiers et coffre avant",
   "Taquet inox"
  ]
 },
 "s_marlin33": {
  "id": "s_marlin33",
  "name": "Marlin 33",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 10.05,
  "cap": null,
  "power": "700 CV",
  "engine": "Suzuki",
  "price": 244700,
  "sold": false,
  "tag": "",
  "blurb": "Dix mètres de semi-rigide premium, bi-motorisation Suzuki.",
  "gallery": [
   "assets/images/boats/s_marlin33/00.jpg",
   "assets/images/boats/s_marlin33/01.jpg",
   "assets/images/boats/s_marlin33/02.jpg",
   "assets/images/boats/s_marlin33/03.jpg",
   "assets/images/boats/s_marlin33/04.jpg"
  ],
  "specsheet": {
   "Longueur": "10.05",
   "Largeur": "3.32",
   "Poids": "2000 Kg",
   "Puissance max": "700",
   "Capacité": "16",
   "Carburant": "480 Lt",
   "Eau": "90 Lt"
  },
  "equip": [
   "Étrave en acier inoxydable et VTR avec passe-amarres et taquets en inox.",
   "Coffre avant et coffre d'ancre avec bain de soleil.",
   "Console de pilotage centrale avec pare-brise, mains courantes latérales en inox, tableau de bord pour instruments en Fenix, panneau de commande électronique 12 fonctions avec gestion numérique BLINK, installation électrique complète, volant en cuir, boussole, feux de navigation, porte coulissante pour accès à la cabine avec serrure, 2 fenêtres latérales avec hublots ouvrants et banquette double orientée vers l'avant.",
   "Aménagement de la cabine avant avec meuble évier en bois, plan en Corian, WC électrique dissimulé, éclairage LED et coussins recouverts de matériau extérieur imperméable.",
   "Cockpit pilote et copilote avec sièges séparés, accoudoir central, meuble bar avec évier, planche à découper, revêtement en Fenix et réfrigérateur de 65 litres.",
   "Aménagement de la poupe avec canapé en U composé de trois coffres indépendants, dossiers périmétraux, table centrale à gaz (option) transformable en large bain de soleil.",
   "Zone plage à l'arrière avec plateformes entièrement recouvertes en EVA, échelle télescopique avec poignée escamotable et poignées périmétrales au ras de l'eau, deux taquets d'amarrage et douche.",
   "Coussins extérieurs complets en mousse à cellules fermées et revêtement SKY lisse.",
   "Revêtement total du pont en EVA.",
   "Réservoir d'eau de 90 litres.",
   "Réservoir d'eaux noires de 40 litres.",
   "Réservoir de carburant de 480 litres.",
   "Guindeau électrique avec télécommande, ancre Trefoil de 7,5 kg en acier inoxydable, 50 mètres de chaîne galvanisée.",
   "Propulseur d'étrave de 140 mm."
  ]
 },
 "s_marlin33w": {
  "id": "s_marlin33w",
  "name": "Marlin 33 Weekender",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 10.05,
  "cap": null,
  "power": "700 CV",
  "engine": "Suzuki",
  "price": 255803,
  "sold": false,
  "tag": "Bientôt",
  "blurb": "La version Weekender du 33 : cabine et confort pour les nuits à bord.",
  "gallery": [
   "assets/images/boats/s_marlin33w/00.jpg",
   "assets/images/boats/s_marlin33w/01.jpg",
   "assets/images/boats/s_marlin33w/02.jpg",
   "assets/images/boats/s_marlin33w/03.jpg",
   "assets/images/boats/s_marlin33w/04.jpg"
  ],
  "specsheet": {
   "Longueur": "10m05",
   "Largeur": "3m32",
   "Poids": "2000 Kg",
   "Puissance max": "700",
   "Capacité": "16 pax",
   "Carburant": "480 Lt",
   "Eau": "90 Lt"
  }
 },
 "s_marlin40": {
  "id": "s_marlin40",
  "name": "Marlin 40",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 12.05,
  "cap": null,
  "power": "1200 CV",
  "engine": "Suzuki",
  "price": 442882,
  "sold": false,
  "tag": "",
  "blurb": "Le vaisseau amiral Marlin : 12 mètres, jusqu'à 1200 CV en trois moteurs.",
  "gallery": [
   "assets/images/boats/s_marlin40/00.jpg",
   "assets/images/boats/s_marlin40/01.jpg",
   "assets/images/boats/s_marlin40/02.jpg",
   "assets/images/boats/s_marlin40/03.jpg",
   "assets/images/boats/s_marlin40/04.jpg"
  ],
  "specsheet": {
   "Longueur": "12m05",
   "Largeur": "3m88",
   "Poids": "3 600 Kg",
   "Puissance max": "1200",
   "Capacité": "16 Pax",
   "Carburant": "820 Lt",
   "Eau": "160 Lt"
  },
  "equip": [
   "Bac à eau noir de 65 litres.",
   "Bancs arrière opposés avec table centrale en teck à commande électrique. Un système de mécanismes de dossier permet de les transformer en dinette, en sièges de navigation orientés vers l’avant ou en bain de soleil",
   "Cabine avant avec paroi et armoire en teck flammé, grand lit double, canapés",
   "Compartiment pilote et copilote avec fauteuils séparés, rangement central sur l’accoudoir, meuble bar avec évier, planche à découper, armoire en teck, portes et couvercle Fenix et réfrigérateur de 90 litres",
   "Console de pilotage centrale avec pare-brise, main courante latérales en acier inox, tableau de bord Fenix pourvu de 18 boutons-poussoirs électroniques avec contrôle numérique BLINK, volant en cuir et acier inox, compas, feux de navigation Lopolight, porte latérale coulissante pour l’accès à la cabine avec serrure, 4 hublots latéraux ouvrables avec rideaux, grand bain de soleil et canapé avant",
   "Coussins de cabine recouverts d’un matériau d’extérieur",
   "Délfiniere de proue avec guide-câble et taquet d’amarrage Seasmart rétractables, guindeau électrique avec télécommande, ancre en acier inox Ultramarine de 12 kg, coffre pour chaîne, cordages, ailes et canapé de proue",
   "Revêtement total en mousse EVA",
   "Réservoir de carburant de 720 litres",
   "Réservoir d’eau de 140 litres extensible à 260litres",
   "Salle de bain séparée avec douche, évier avec meuble et plan en Corian,",
   "Salle technique",
   "Sellerie complète en polyuréthane à cellule fermée et revêtement Silvertex",
   "Système électrique 12V digital BLINK, batterie de service 140Ah et chargeur de batterie à terre avec câble",
   "WC électriques et bac à eau noire",
   "Zone de plage arrière de cinq mètres carrés, bordée de mousse EVA, avec marchepieds, deux échelles télescopiques avec poignées rétractables et barre d’appui périphérique encastrée, deux bornes d’amarrage Seasmart rétractables et douche",
   "Éclairage de courtoisie du cockpit à leds blanches"
  ]
 },
 "s_randsource22": {
  "id": "s_randsource22",
  "name": "RAND Source 22",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 6.7,
  "cap": null,
  "power": "250 CV",
  "engine": "Mercury",
  "price": 83880,
  "sold": false,
  "tag": "",
  "blurb": "Le day-boat scandinave à plage avant immense, signé Rand.",
  "gallery": [
   "assets/images/boats/s_randsource22/00.jpg",
   "assets/images/boats/s_randsource22/01.jpg",
   "assets/images/boats/s_randsource22/02.jpg",
   "assets/images/boats/s_randsource22/03.jpg",
   "assets/images/boats/s_randsource22/04.jpg"
  ],
  "specsheet": {
   "Longueur": "6m70",
   "Largeur": "2m30",
   "Poids": "950 Kg",
   "Puissance max": "250",
   "Capacité": "12 pax",
   "Carburant": "198 Lt",
   "Eau": "40 Lt",
   "Coque": "Polyester"
  },
  "equip": [
   "6x taquets retractables en acier inoxydables",
   "Anneau de remorquage",
   "Bain de soleil arrière convertible",
   "Bain de soleil convertible à l'arrière",
   "Batterie 2 X 90 Ah",
   "Cockpit Auto-videur",
   "Console centrale avec pare-brise",
   "Crochet pour sports nautiques",
   "Echelle de bain standard",
   "Mains-courantes à l'avant",
   "Pompe de cale",
   "Sièges de barre convertibles en sièges orientés vers l'arrière",
   "Stockage pour pare-battages, bimini etc.",
   "Système stéréo avec Bluetooth",
   "Table de cockpit en teck",
   "Teck synthétique Weathered dans le cockpit et la",
   "Volant sport",
   "plateforme de bain",
   "Écran tactile de 9'' avec commandes de barre interactives"
  ]
 },
 "s_randsuprem27": {
  "id": "s_randsuprem27",
  "name": "RAND Suprem 27",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 8.44,
  "cap": null,
  "power": "350 CV",
  "engine": "Mercury",
  "price": 178680,
  "sold": false,
  "tag": "",
  "blurb": "Élégance danoise et volumes de pont exceptionnels.",
  "gallery": [
   "assets/images/boats/s_randsuprem27/00.jpg",
   "assets/images/boats/s_randsuprem27/01.jpg",
   "assets/images/boats/s_randsuprem27/02.jpg",
   "assets/images/boats/s_randsuprem27/03.jpg",
   "assets/images/boats/s_randsuprem27/04.jpg"
  ],
  "specsheet": {
   "Longueur": "8m44",
   "Largeur": "2m59",
   "Poids": "1 550 Kg",
   "Puissance max": "350",
   "Capacité": "12 pax",
   "Carburant": "315 Lt",
   "Eau": "50 Lt",
   "Coque": "Polyester"
  },
  "equip": [
   "2x GPS 7 ” commandes interactives",
   "2x Taquets d'amarrage en acier inoxydable + chaumards dans la baille à mouillage",
   "4x taquets retractables en acier inoxydable",
   "6x porte-gobelets en acier inoxydable",
   "Anneau de Remorquage d'étrave",
   "Bain de soleil arrière convertible",
   "Batteries 2 X 90 Ah",
   "Casier de ski nautique et de wakeboard à l'arrière",
   "Cockpit et baille à mouillage auto-videur",
   "Extincteur",
   "Feu de navigation et position LED",
   "Haut parleur",
   "Liston de 52 mm avec embouts en acier inoxydable",
   "Mains courantes de grand diamètre sur le pare-brise",
   "Plateforme de bain allongée avec échelle de bain",
   "Pompe de cale électrique et manuelle",
   "Sièges de barre convertibles en banquette U complète",
   "Système stéréo",
   "Teck synthétique dans le cockpit et le pont avant",
   "Toilettes portables",
   "Volant sport et tableau de bord en fibre de carbone antireflet"
  ]
 },
 "s_randroamer28": {
  "id": "s_randroamer28",
  "name": "RAND Roamer 28",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 8.82,
  "cap": null,
  "power": "500 CV",
  "engine": "Mercury",
  "price": 227880,
  "sold": false,
  "tag": "",
  "blurb": "Le Roamer 28 : hard-top verre, polyvalence pêche, plongée et croisière.",
  "gallery": [
   "assets/images/boats/s_randroamer28/00.jpg",
   "assets/images/boats/s_randroamer28/01.jpg",
   "assets/images/boats/s_randroamer28/02.jpg",
   "assets/images/boats/s_randroamer28/03.jpg",
   "assets/images/boats/s_randroamer28/04.jpg"
  ],
  "specsheet": {
   "Longueur": "8m82",
   "Largeur": "2m72",
   "Poids": "1 750 Kg",
   "Puissance max": "500",
   "Capacité": "8 pax",
   "Carburant": "315 Lt",
   "Eau": "50 Lt",
   "Coque": "Polyester"
  },
  "equip": [
   "2 écrans tactiles de 9 pouces avec commandes de barre interactives",
   "6 taquets d'amarrage rétractables en acier inoxydable",
   "Batterie 2 X 90 Ah",
   "Extincteur",
   "Feu de navigation et de position à LED",
   "Grand espace de rangement pour les pare-battages, l'équipement de pêche, plongée…",
   "Hard-Top en verre avec côtés ouverts",
   "Liston en caoutchouc de 125 mm",
   "Pompe de cale électrique et manuelle",
   "Sièges de barre à suspension sport avec réglage complet et pivots vers l'arrière",
   "Sièges et dossiers arrière convertibles",
   "Système d'auto-vidange en mer",
   "Système stéréo Fusion avec. 4 haut-parleurs",
   "Toilettes manuelles avec Pompe manuelle",
   "Volant sport et pare-brise antireflet",
   "Échelle de bain télescopique"
  ]
 },
 "s_randarchi32": {
  "id": "s_randarchi32",
  "name": "RAND Archipelago 32",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 9.95,
  "cap": null,
  "power": "600 CV",
  "engine": "Mercury",
  "price": 299880,
  "sold": false,
  "tag": "",
  "blurb": "Un grand day-boat scandinave, bi-motorisation et finitions haut de gamme.",
  "gallery": [
   "assets/images/boats/s_randarchi32/00.jpg",
   "assets/images/boats/s_randarchi32/01.jpg",
   "assets/images/boats/s_randarchi32/02.jpg",
   "assets/images/boats/s_randarchi32/03.jpg",
   "assets/images/boats/s_randarchi32/04.jpg"
  ],
  "specsheet": {
   "Longueur": "9m95",
   "Largeur": "2m89",
   "Poids": "3 000 Kg",
   "Puissance max": "600",
   "Capacité": "12 pax",
   "Carburant": "512 Lt",
   "Eau": "100 Lt",
   "Coque": "Polyester"
  },
  "equip": [
   "2 armoires avec étagères",
   "2 prises USB",
   "2 écrans tactiles de 9 pouces avec commandes de barre interactives",
   "6x taquets retractables en acier inoxydable",
   "Anneau de Remorquage d'étrave",
   "Bain de soleil arrière convertible",
   "Batterie 2 X 90 Ah",
   "Capteur de profondeur",
   "Casier de ski nautique et de wakeboard à l'arrière",
   "Cockpit et baille à mouillage auto-videur",
   "Compartiment de rangement pour les objets personnels",
   "Crochet pour sports nautiques",
   "Echelle de bain",
   "Fenêtres panoramiques",
   "Feu de navigation et position LED",
   "Grand lit double",
   "Hard-Top avec Dôme en verre et côtés ouverts",
   "Pompe de cale électrique et manuelle",
   "Réservoir d'eau noire",
   "Système stéréo avec. Bluetooth et USB",
   "Teck synthétique dans le cockpit et le pont avant",
   "Toilettes manuelles avec. Pompe manuelle"
  ]
 },
 "s_randrealm44": {
  "id": "s_randrealm44",
  "name": "RAND Realm 44",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 13.5,
  "cap": null,
  "power": "800 CV",
  "engine": "Mercruiser",
  "price": 399900,
  "sold": false,
  "tag": "",
  "blurb": "Le flagship Rand : 13,5 m, V8 Mercruiser, l'art de vivre danois en mer.",
  "gallery": [
   "assets/images/boats/s_randrealm44/00.jpg",
   "assets/images/boats/s_randrealm44/01.jpg",
   "assets/images/boats/s_randrealm44/02.jpg",
   "assets/images/boats/s_randrealm44/03.jpg",
   "assets/images/boats/s_randrealm44/04.jpg"
  ],
  "specsheet": {
   "Longueur": "13.50",
   "Largeur": "3.99",
   "Poids": "6500 Kg",
   "Puissance max": "800",
   "Capacité": "12"
  },
  "equip": [
   "Équipement du pont :",
   "Hard-Top avec dome en verre et côtés ouverts",
   "6x taquets d’amarrage rétractables en acier inoxydable",
   "Porte d’embarquement tribord",
   "Salon rabattable bâbord",
   "Plate-forme de bain allongée avec échelle de bain",
   "Rails de préhension à l’avant et à l’arrière",
   "Bain de soleil arrière convertible",
   "Bain de soleil d’arc avec dossier inclinable",
   "Lumières de pont à LED",
   "Crochet pour sports nautiques",
   "Mât et support de drapeau 8x Ailes et supports",
   "Prise 220/110V dans le stockage des jouets nautiques",
   "Équipement de cabine et de toilettes :",
   "Canapé convertible en U et lit double",
   "Cabine intermédiaire avec lits jumeaux",
   "Fenêtres panoramiques",
   "Lucarne",
   "Prises USB-C dans la cabine",
   "4x prises 220V/110V dans la cabine",
   "Toilettes électriques",
   "Cabine de douche séparée",
   "Équipement de la cuisine :",
   "Réfrigérateur",
   "Évier",
   "Poste de pilotage :",
   "Réglage des sièges de barre Trible",
   "Système stéréo",
   "Batterie au lithium et onduleur pour grande maison",
   "Essuie-glace",
   "Propulseur d'étrave",
   "Guindeau électrique et ancre",
   "Alimentation à quai",
   "Écrans tactiles 3x12\" avec commandes de barre interactives",
   "Pilote automatique",
   "Sondeur"
  ]
 },
 "s_protagon20": {
  "id": "s_protagon20",
  "name": "Protagon 20",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 5.95,
  "cap": null,
  "power": "200 CV",
  "engine": "Selva",
  "price": 46960,
  "sold": false,
  "tag": "",
  "blurb": "Un day-boat compact et racé, parfait premier bateau.",
  "gallery": [
   "assets/images/boats/s_protagon20/00.jpg",
   "assets/images/boats/s_protagon20/01.jpg",
   "assets/images/boats/s_protagon20/02.jpg",
   "assets/images/boats/s_protagon20/03.jpg"
  ],
  "specsheet": {
   "Longueur": "5m95",
   "Largeur": "2m30",
   "Poids": "850 Kg",
   "Puissance max": "200",
   "Capacité": "9 Cat. C",
   "Carburant": "140 Lt",
   "Eau": "55 Lt",
   "Coque": "Polyester"
  },
  "equip": [
   "Couleur de la console et des sièges gris graphite",
   "Couleur standard blanc",
   "Coussin de poupe",
   "Coussin de proue",
   "Couverture en mousse dans le compartiment de l'ancre et le support de drisse",
   "Direction hydraulique",
   "Echelle de bains en inox 316 l",
   "Feux de Navigation",
   "Main courante en inox 316 l",
   "Panneau interrupteurs version luxe",
   "Prise usb",
   "Rouleau de proue",
   "Réservoir de carburant de 140 litres",
   "Siège avant console",
   "Siège debout avec lavabo",
   "Tableau de bord version luxe"
  ]
 },
 "s_protagon25": {
  "id": "s_protagon25",
  "name": "Protagon 25 Center Console",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 8.0,
  "cap": null,
  "power": "300 CV",
  "engine": "Selva",
  "price": 79270,
  "sold": false,
  "tag": "",
  "blurb": "Center console de 8 m, design épuré et grande habitabilité.",
  "gallery": [
   "assets/images/boats/s_protagon25/00.jpg"
  ],
  "specsheet": {
   "Longueur": "8m00",
   "Largeur": "2m45",
   "Poids": "1400 Kg",
   "Puissance max": "300",
   "Capacité": "12 Cat. C",
   "Carburant": "250 Lt",
   "Eau": "55 Lt",
   "Coque": "Polyester"
  },
  "equip": [
   "Couverture en mousse dans le compartiment de l'ancre et le support de drisse",
   "Direction hydraulique",
   "Dossier inclinable du siège arrière",
   "Evier dans le meuble bar et dans toilettes",
   "Extension de la table et du bain de soleil à l'arrière",
   "Extensions du bain de soleil de Proue",
   "Grande console avec toilette",
   "Jeu complet de mains courantes en acier inoxydable 316 l",
   "Main courante en acier inox peinte en noir",
   "Meuble bar dans la zone des sièges du conducteur et du passager",
   "Plates-formes arrière avec échelle de bain",
   "Pompe de cale automatique",
   "Radio - 4 haut-parleurs marins",
   "Réservoir de carburant de 250 litres",
   "Siège avant console",
   "Système de douche dans la toilettes et sur le pont",
   "Système électrique",
   "Toilettes électriques avec réservoir d'eaux noires",
   "Éclairage sur le pont et dans les compartiments"
  ]
 },
 "s_protagon33": {
  "id": "s_protagon33",
  "name": "Protagon 33",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 10.95,
  "cap": null,
  "power": "700 CV",
  "engine": "Selva",
  "price": 260020,
  "sold": false,
  "tag": "",
  "blurb": "Le plus grand Protagon : presque 11 m de sportivité et de confort.",
  "gallery": [
   "assets/images/boats/s_protagon33/00.jpg",
   "assets/images/boats/s_protagon33/01.jpg",
   "assets/images/boats/s_protagon33/02.jpg",
   "assets/images/boats/s_protagon33/03.jpg",
   "assets/images/boats/s_protagon33/04.jpg"
  ],
  "specsheet": {
   "Longueur": "10m95",
   "Largeur": "3m10",
   "Poids": "3800 Kg",
   "Puissance max": "700",
   "Capacité": "8 Cat. B",
   "Carburant": "650 Lt",
   "Eau": "100 Lt",
   "Coque": "Polyester"
  },
  "equip": [
   "•Strat superficiel carène en résine vinylester Carène à double",
   "step avec V profond et capacité offshore Étrave verticale de",
   "type «wave piercing»",
   "•Gelcoat coque et pont blanc signal – RAL 9003",
   "•Pont sur un seul niveau",
   "•Revêtement de pont en mousse EVA (marron ou gris foncé)",
   "Balcons latéraux ouvrants électriquement",
   "•Hard-top en PRV avec structure en acier inox noir",
   "•Pare-brise en verre trempé pleine hauteur",
   "•Essuie-glace",
   "•Corne de brume",
   "•Échelle de bain télescopique en acier inoxydable",
   "•6 taquets d’amarrage en acier inoxydable",
   "•Mains courantes intégrées en acier inox sur le pont",
   "•Poignées sur siège de console et assise du wet bar",
   "•6 systèmes de fixation rapide pour pare-battages de chaque",
   "côté",
   "•Réservoir de carburant de 650 L avec sonde",
   "•Toilettes électriques dans la console avec réservoir d’eaux noires",
   "•Cabine toilette avec lavabo",
   "•Douche intérieure",
   "•Douche de pont",
   "•Prise USB",
   "•Trois configurations de poupe personnalisables",
   "•Dossier de poupe télescopique Jeu complet de coussins",
   "•Bains de soleil avant et arrière",
   "•Table de proue",
   "•Table de poupe",
   "•Éclairage de pont",
   "•Système audio Fusion avec 6 haut-parleurs Réfrigérateur",
   "électrique dans le wet bar",
   "•Guindeau électrique 1000 W avec davier d’étrave, ancre inox",
   "et chaîne galvanisée de 8 mm",
   "•Wet bar avec évier et deux porte-gobelets",
   "•Tableau de commande de luxe",
   "•Compas 3 sièges baquets au poste de pilotage",
   "•3 options de sellerie (chocolat, beige et gris foncé)",
   "•Coutures diamant premium",
   "•Porte-gobelets gainés",
   "•Volant en cuir",
   "3 pompes de cale électriques Mât de hard-top avec feux de",
   "navigation"
  ]
 },
 "s_selva540": {
  "id": "s_selva540",
  "name": "Selva 540 Open",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 5.4,
  "cap": null,
  "power": "80 CV",
  "engine": "Selva",
  "price": 21990,
  "sold": false,
  "tag": "",
  "blurb": "L'entrée de gamme Selva : léger, économique, idéal débutants.",
  "gallery": [
   "assets/images/boats/s_selva540/00.jpg",
   "assets/images/boats/s_selva540/01.jpg",
   "assets/images/boats/s_selva540/02.jpg",
   "assets/images/boats/s_selva540/03.jpg"
  ],
  "specsheet": {
   "Longueur": "5m40",
   "Largeur": "2m19",
   "Poids": "450 Kg",
   "Puissance max": "80",
   "Capacité": "7 Cat. C",
   "Carburant": "60 Lt (optionnel)",
   "Eau": "50 Lt (optionnel)",
   "Coque": "Polyester"
  },
  "equip": [
   "Accessoires en plastique",
   "Boîtier de batterie",
   "Clapets antiretour",
   "Console, pare-brise, etc",
   "Echelle de bain télescopique en inox",
   "Feux de Navigation Led",
   "Main Courante ouvert en inox",
   "Main courante de poupe en inox",
   "Profil parabattage",
   "Puisard autovidant",
   "Rouleau d'ancre de proue en inox",
   "Siège pilote et copilote avec coussins",
   "Timonerie Heavy duty"
  ]
 },
 "s_selva560": {
  "id": "s_selva560",
  "name": "Selva 560 Wide Open",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 5.6,
  "cap": null,
  "power": "80 CV",
  "engine": "Selva",
  "price": 21240,
  "sold": false,
  "tag": "",
  "blurb": "Version Wide Open, plus de largeur et de stabilité.",
  "gallery": [
   "assets/images/boats/s_selva560/00.jpg",
   "assets/images/boats/s_selva560/01.jpg",
   "assets/images/boats/s_selva560/02.jpg",
   "assets/images/boats/s_selva560/03.jpg"
  ],
  "specsheet": {
   "Longueur": "5m60",
   "Largeur": "2m02",
   "Poids": "450 Kg",
   "Puissance max": "80",
   "Capacité": "8 Cat. C",
   "Carburant": "50 Lt (optionnel)",
   "Eau": "50 Lt (optionnel)",
   "Coque": "Polyester"
  },
  "equip": [
   "Boîtier de batterie",
   "Clapets antiretour",
   "Echelle de bain en Inox",
   "Feux de Navigation Led",
   "Main courante de poupe en inox",
   "Main courante de proue en inox",
   "Panneau interrupteurs avec prise",
   "Puisard autovidant"
  ]
 },
 "s_selva580": {
  "id": "s_selva580",
  "name": "Selva 580 Open",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 5.8,
  "cap": null,
  "power": "115 CV",
  "engine": "Selva",
  "price": 23990,
  "sold": false,
  "tag": "",
  "blurb": "Un open familial polyvalent, jusqu'à 115 CV.",
  "gallery": [
   "assets/images/boats/s_selva580/00.jpg",
   "assets/images/boats/s_selva580/01.jpg",
   "assets/images/boats/s_selva580/02.jpg",
   "assets/images/boats/s_selva580/03.jpg"
  ],
  "specsheet": {
   "Longueur": "5m80",
   "Largeur": "2m19",
   "Poids": "550 Kg",
   "Puissance max": "115",
   "Capacité": "8 Cat. C",
   "Carburant": "60 Lt (optionnel)",
   "Eau": "50 Lt (optionnel)",
   "Coque": "Polyester"
  },
  "equip": [
   "Accessoires en plastique",
   "Boîtier de batterie",
   "Clapets antiretour",
   "Console, pare-brise, etc",
   "Echelle de bain télescopique en inox",
   "Feux de Navigation Led",
   "Main Courante de poupe en inox",
   "Main Courante ouvert en inox",
   "Panneau interrupteurs avec prise",
   "Profil parabattage",
   "Puisard autovidant",
   "Rouleau d'ancre de proue en inox",
   "Siège avant console avec coussin",
   "Siège pilote et copilote avec coussins",
   "Timonerie Heavy duty"
  ]
 },
 "s_selva590": {
  "id": "s_selva590",
  "name": "Selva 590 FishMaster",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 5.9,
  "cap": null,
  "power": "115 CV",
  "engine": "Selva",
  "price": 38780,
  "sold": false,
  "tag": "",
  "blurb": "La version FishMaster, équipée pour la pêche embarquée.",
  "gallery": [
   "assets/images/boats/s_selva590/00.jpg",
   "assets/images/boats/s_selva590/01.jpg",
   "assets/images/boats/s_selva590/02.jpg",
   "assets/images/boats/s_selva590/03.jpg"
  ],
  "specsheet": {
   "Longueur": "5m90",
   "Largeur": "2m42",
   "Poids": "900 Kg",
   "Puissance max": "115",
   "Capacité": "7 Cat. C",
   "Carburant": "100 Lt",
   "Eau": "30 Lt (optionnel)",
   "Coque": "Polyester"
  },
  "equip": [
   "Boîtier de batterie",
   "Clapets antiretour",
   "Echelle de bain",
   "Essuie-glaces",
   "Fenêtres latérales",
   "Feux de Navigation Led",
   "Gazinière - évier marin",
   "Jeu complet de coussins",
   "Main courante de proue et de poupe en inox",
   "Panneau interrupteurs avec prise",
   "Pare-brise en verre trempé",
   "Profil parabattage",
   "Puisard autovidant",
   "Rouleau d'ancre de proue en inox",
   "Réservoir carburant 100 L",
   "Timonerie Heavy duty",
   "Trou d'homme de la cabine et du rouf",
   "Éclairage intérieur de cabine"
  ]
 },
 "s_selva665": {
  "id": "s_selva665",
  "name": "Selva 665 Open",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 6.7,
  "cap": null,
  "power": "150 CV",
  "engine": "Selva",
  "price": 40730,
  "sold": false,
  "tag": "",
  "blurb": "Un open de 6,70 m, console centrale et grand cockpit.",
  "gallery": [
   "assets/images/boats/s_selva665/00.jpg",
   "assets/images/boats/s_selva665/01.jpg",
   "assets/images/boats/s_selva665/02.jpg",
   "assets/images/boats/s_selva665/03.jpg"
  ],
  "specsheet": {
   "Longueur": "6m70",
   "Largeur": "2m35",
   "Poids": "750 Kg",
   "Puissance max": "150",
   "Capacité": "10 Cat. C",
   "Carburant": "100 Lt",
   "Eau": "55 Lt (optionnel)",
   "Coque": "Polyester"
  },
  "equip": [
   "Console, pare-brise, etc.",
   "Siège avant de console avec coussin",
   "Jeu de coussins de proue (3 pièces)",
   "Coussin de poupe",
   "Dossier de poupe rabattable",
   "Sièges pilote et copilote avec coussins",
   "Réservoir carburant 100 L",
   "Plateformes de bain",
   "Coque à redan",
   "Direction hydraulique",
   "Balustrade avant ouverte en inox",
   "Main-courante arrière en acier inoxydable",
   "Echelle de bain télescopique en acier",
   "Rouleau de proue en inox",
   "Feux de navigation à LED",
   "Feu de mouillage à LED",
   "Panneau de contrôle avec prise",
   "Coffre à batterie",
   "Profil de pare-battage",
   "Cockpit auto-videur",
   "Couleur standard blanc"
  ]
 },
 "s_selva670": {
  "id": "s_selva670",
  "name": "Selva 670 FishMaster",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 6.7,
  "cap": null,
  "power": "250 CV",
  "engine": "Selva",
  "price": 62570,
  "sold": false,
  "tag": "",
  "blurb": "FishMaster de 6,70 m, motorisable jusqu'à 250 CV.",
  "gallery": [
   "assets/images/boats/s_selva670/00.jpg",
   "assets/images/boats/s_selva670/01.jpg",
   "assets/images/boats/s_selva670/02.jpg",
   "assets/images/boats/s_selva670/03.jpg",
   "assets/images/boats/s_selva670/04.jpg"
  ],
  "specsheet": {
   "Longueur": "6m70",
   "Largeur": "2m47",
   "Poids": "1250 Kg",
   "Puissance max": "250",
   "Capacité": "8 Cat. C",
   "Carburant": "150 Lt",
   "Eau": "50 Lt",
   "Coque": "Polyester"
  },
  "equip": [
   "Boîtier de batterie",
   "Clapets antiretour",
   "Echelle de bain",
   "Essuie-glaces",
   "Fenêtres latérales",
   "Feux de Navigation Led",
   "Gazinière - évier marin",
   "Jeu complet de coussins",
   "Main courante de proue et de poupe en inox",
   "Panneau interrupteurs avec prise",
   "Pare-brise en verre trempé",
   "Porte coulissante pour accès à la cabine",
   "Profil parabattage",
   "Puisard autovidant",
   "Revêtement de pont en mousse eva",
   "Réservoir carburant 150 L",
   "Salle de bains séparé",
   "Système de douche dans les toilettes et dans le cockpit",
   "Table dans la cabine",
   "Timonerie Heavy duty",
   "Trou d'homme de la cabine et du rouf",
   "Éclairage intérieur de cabine"
  ]
 },
 "s_selva21lv": {
  "id": "s_selva21lv",
  "name": "Selva 21 LV Plus",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 6.3,
  "cap": null,
  "power": "150 CV",
  "engine": "Selva",
  "price": 45880,
  "sold": false,
  "tag": "",
  "blurb": "Le 21 LV Plus, cabine et confort dans 6,30 m.",
  "gallery": [
   "assets/images/boats/s_selva21lv/00.jpg",
   "assets/images/boats/s_selva21lv/01.jpg",
   "assets/images/boats/s_selva21lv/02.jpg"
  ],
  "specsheet": {
   "Longueur": "6m30",
   "Largeur": "2m63",
   "Poids": "580 Kg",
   "Puissance max": "150",
   "Capacité": "14 Cat. D – 10 Cat. C",
   "Carburant": "130 Lt",
   "Eau": "30 Lt"
  },
  "equip": [
   "Boudin tricolore",
   "Canapé de poupe en forme de U convertible en solarium, avec table centrale et coussins",
   "Coussin pour rallonge bain de soleil avant",
   "Coussins Plus Bicolore",
   "Double plage de bain arrière VTR avec échelle pliable",
   "Installation de douche complète avec réservoir d'eau douce 30 Lt",
   "Installation moteur (pour moteurs Selva)",
   "Installation électrique complète",
   "Panneau métallique porte-interrupteurs avec interrupteurs encastrés",
   "Pompe de cale à immersion",
   "Rallonge bain de soleil avant",
   "Réservoir à carburant de 130 Lt",
   "Salon de proue en forme de V convertible en bain de soleil",
   "Set de coussins bain de soleil avant",
   "Siège pilote pour conduite semi-debout avec coffre étanche + coussin",
   "Table / extension du bain de soleil central de proue avec coussins",
   "Tableau de bord avec instruments moteur",
   "Volant spécial plus"
  ]
 },
 "s_selva21lvu": {
  "id": "s_selva21lvu",
  "name": "Selva 21 LV Plus Ultra",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 6.3,
  "cap": null,
  "power": "150 CV",
  "engine": "Selva",
  "price": 50690,
  "sold": false,
  "tag": "",
  "blurb": "Version Ultra, finitions et équipements supérieurs.",
  "gallery": [
   "assets/images/boats/s_selva21lvu/00.jpg",
   "assets/images/boats/s_selva21lvu/01.jpg",
   "assets/images/boats/s_selva21lvu/02.jpg"
  ],
  "specsheet": {
   "Longueur": "6m30",
   "Largeur": "2m63",
   "Poids": "580 Kg",
   "Puissance max": "150",
   "Capacité": "14 Cat. D – 10 Cat. C",
   "Carburant": "130 Lt",
   "Eau": "30 Lt"
  },
  "equip": [
   "Boudin tricolore Version Ultra",
   "Canapé de poupe en forme de U convertible en solarium, avec table centrale et coussins",
   "Console complète avec main courante en acier inoxydable, commande à distance",
   "Coussins Spéciaux Ultra",
   "Double plage de bain arrière VTR avec échelle pliable",
   "Fibre de Verre Gris Ultra",
   "Installation de douche complète avec réservoir d'eau douce 30 Lt",
   "Installation moteur (pour moteurs Selva)",
   "Installation électrique complète",
   "Kit Sea Deck, pont complet",
   "Panneau métallique porte-interrupteurs avec interrupteurs encastrés",
   "Rallonge bain de soleil avant",
   "Réservoir à carburant de 130 Lt",
   "Salon de proue en forme de V convertible en bain de soleil",
   "Set de coussins bain de soleil avant",
   "Siège pilote pour conduite semi-debout avec coffre étanche + coussin",
   "Table / extension du bain de soleil central de proue avec coussins",
   "Tableau de bord avec instruments moteur",
   "Volant spécial plus"
  ]
 },
 "s_selva650": {
  "id": "s_selva650",
  "name": "Selva 650 Stile",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 6.5,
  "cap": null,
  "power": "175 CV",
  "engine": "Selva",
  "price": 58170,
  "sold": false,
  "tag": "",
  "blurb": "La ligne Stile italienne : élégance et plaisir de navigation.",
  "gallery": [
   "assets/images/boats/s_selva650/00.jpg",
   "assets/images/boats/s_selva650/01.jpg",
   "assets/images/boats/s_selva650/02.jpg"
  ],
  "specsheet": {
   "Longueur": "6m50",
   "Largeur": "2m60",
   "Poids": "580 Kg",
   "Puissance max": "175",
   "Capacité": "12 Cat. C",
   "Carburant": "175 Lt",
   "Eau": "40 Lt"
  },
  "equip": [
   "Canapé arrière convertible en bain de soleil",
   "Console complète Stile Line - main courante en acier inoxydable, boîtier télécommande mono-levier, volant anatomique, direction hydraulique, pare-brise anti-éblouissant, porte verrouillable, siège avant avec coussin et accès au coffre en dessous et coussin de dossier",
   "Coussin pour rallonge bain de soleil avant",
   "Coussins STILE LINE en deux couleurs Colorado/Gange",
   "Installation de douche complète avec réservoir d’eau douce intégrée",
   "Installation moteur",
   "Installation électrique complète",
   "Panneau porte-interrupteurs avec interrupteurs",
   "Pompe de cale à immersion",
   "Rallonge bain de soleil arrière avec coussins",
   "Rallonge bain de soleil avant",
   "Réservoir de carburant intégré, monté en conformité aux normes CE avec blower, tube de refoulement avec filtres décanteurs et électrovannes, tube d’embarquement, évent et indicateur de niveau",
   "Set de coussins bain de soleil avant",
   "Siège de conduite multifonctions - siège Pilote semi- debout avec coussin et accès au coffre inférieur",
   "Tableau de bord à extension totale",
   "Volant Selva Sport"
  ]
 },
 "s_selva700": {
  "id": "s_selva700",
  "name": "Selva 700 Stile",
  "kind": "acheter",
  "cat": "neuf",
  "color": "",
  "length": 6.99,
  "cap": null,
  "power": "300 CV",
  "engine": "Selva",
  "price": 82710,
  "sold": false,
  "tag": "",
  "blurb": "Le plus grand Stile, presque 7 m de raffinement.",
  "gallery": [
   "assets/images/boats/s_selva700/00.jpg",
   "assets/images/boats/s_selva700/01.jpg",
   "assets/images/boats/s_selva700/02.jpg",
   "assets/images/boats/s_selva700/03.jpg"
  ],
  "specsheet": {
   "Longueur": "6m99",
   "Largeur": "2m76",
   "Poids": "1000 Kg",
   "Puissance max": "300",
   "Capacité": "14 Cat. C",
   "Carburant": "200 Lt",
   "Eau": "50 Lt"
  },
  "equip": [
   "Canapé arrière convertible en bain de soleil",
   "Console complète Stile Line - main courante en acier inoxydable, boîtier télécommande mono-levier, volant anatomique, direction hydraulique, pare-brise anti-éblouissant, porte verrouillable, siège avant avec coussin et accès au coffre en dessous et coussin de dossier",
   "Coussin pour rallonge bain de soleil avant",
   "Coussins STILE LINE en deux couleurs Colorado/Gange",
   "Installation de douche complète avec réservoir d’eau douce intégrée",
   "Installation moteur",
   "Installation électrique complète",
   "Panneau porte-interrupteurs avec interrupteurs",
   "Pompe de cale à immersion",
   "Rallonge bain de soleil arrière avec coussins",
   "Rallonge bain de soleil avant",
   "Réservoir de carburant intégré, monté en conformité aux normes CE avec blower, tube de refoulement avec filtres décanteurs et électrovannes, tube d’embarquement, évent et indicateur de niveau",
   "Set de coussins bain de soleil avant",
   "Siège de conduite multifonctions - siège Pilote semi- debout avec coussin et accès au coffre inférieur",
   "Tableau de bord à extension totale",
   "Volant Selva Sport"
  ]
 },
 "o_capelli626": {
  "id": "o_capelli626",
  "name": "Capelli 626 – Refit 2025",
  "kind": "acheter",
  "cat": "occasion",
  "color": "",
  "length": 6.26,
  "cap": null,
  "power": "150 CV",
  "engine": "Suzuki",
  "price": 40000,
  "sold": false,
  "tag": "Refit 2025",
  "blurb": "Refait à neuf par nos ateliers, livré avec sa remorque.",
  "gallery": [
   "assets/images/boats/o_capelli626/00.jpg",
   "assets/images/boats/o_capelli626/01.jpg",
   "assets/images/boats/o_capelli626/02.jpg",
   "assets/images/boats/o_capelli626/03.jpg",
   "assets/images/boats/o_capelli626/04.jpg"
  ],
  "specsheet": {
   "Longueur": "6.26",
   "Largeur": "2.6",
   "Puissance max": "150",
   "Capacité": "12 pax",
   "Carburant": "120 Lt",
   "Eau": "42 Lt"
  }
 },
 "o_eider760": {
  "id": "o_eider760",
  "name": "EIDER Fish Rover 760",
  "kind": "acheter",
  "cat": "occasion",
  "color": "",
  "length": 7.2,
  "cap": null,
  "power": "230 CV",
  "engine": "Volvo Penta",
  "price": 15000,
  "sold": false,
  "tag": "",
  "blurb": "Un fish-rover robuste, cabine et timonerie, prêt à naviguer.",
  "gallery": [
   "assets/images/boats/o_eider760/00.jpg",
   "assets/images/boats/o_eider760/01.jpg",
   "assets/images/boats/o_eider760/02.jpg",
   "assets/images/boats/o_eider760/03.jpg",
   "assets/images/boats/o_eider760/04.jpg"
  ],
  "specsheet": {
   "Longueur": "7m20",
   "Largeur": "2m66",
   "Puissance max": "230",
   "Capacité": "6 pax",
   "Carburant": "180 Lt",
   "Eau": "50 Lt"
  }
 },
 "o_marlin24sr": {
  "id": "o_marlin24sr",
  "name": "Marlin 24 SR – Refit 2025",
  "kind": "acheter",
  "cat": "occasion",
  "color": "",
  "length": 7.4,
  "cap": null,
  "power": "250 CV",
  "engine": "Suzuki",
  "price": 60000,
  "sold": false,
  "tag": "Refit 2025",
  "blurb": "Notre 24 SR d'occasion, entièrement refait en 2025.",
  "gallery": [
   "assets/images/boats/o_marlin24sr/00.jpg",
   "assets/images/boats/o_marlin24sr/01.jpg",
   "assets/images/boats/o_marlin24sr/02.jpg",
   "assets/images/boats/o_marlin24sr/03.jpg",
   "assets/images/boats/o_marlin24sr/04.jpg"
  ],
  "specsheet": {
   "Longueur": "7m40",
   "Largeur": "2m98",
   "Poids": "1050 Kg",
   "Puissance max": "250",
   "Capacité": "14 Cat. D – 12 Cat. C",
   "Carburant": "220 Lt",
   "Eau": "42 Lt"
  }
 },
 "o_jeanneau805": {
  "id": "o_jeanneau805",
  "name": "Jeanneau Leader 805",
  "kind": "acheter",
  "cat": "occasion",
  "color": "",
  "length": 7.49,
  "cap": null,
  "power": "380 CV",
  "engine": "Mercruiser",
  "price": 35000,
  "sold": true,
  "tag": "",
  "blurb": "Un day-cruiser cabine polyvalent — désormais vendu.",
  "gallery": [
   "assets/images/boats/o_jeanneau805/00.jpg",
   "assets/images/boats/o_jeanneau805/01.jpg"
  ],
  "specsheet": {
   "Longueur": "7m49",
   "Largeur": "2m95",
   "Puissance max": "320",
   "Capacité": "8 Pax",
   "Carburant": "320 Lt",
   "Eau": "100 Lt",
   "Coque": "Polyester"
  }
 },
 "o_airon277": {
  "id": "o_airon277",
  "name": "Airon Marine 277",
  "kind": "acheter",
  "cat": "occasion",
  "color": "",
  "length": 8.2,
  "cap": null,
  "power": "320 CV",
  "engine": "Volvo Penta",
  "price": 15000,
  "sold": true,
  "tag": "",
  "blurb": "Runabout sportif italien — désormais vendu.",
  "gallery": [
   "assets/images/boats/o_airon277/00.jpg",
   "assets/images/boats/o_airon277/01.jpg"
  ],
  "specsheet": {
   "Longueur": "8.20",
   "Largeur": "250",
   "Puissance max": "320",
   "Capacité": "8"
  }
 },
 "o_capelli900": {
  "id": "o_capelli900",
  "name": "Capelli Tempest 900 WA",
  "kind": "acheter",
  "cat": "occasion",
  "color": "",
  "length": 9.3,
  "cap": null,
  "power": "2 x 250 CV",
  "engine": "Yamaha",
  "price": 58000,
  "sold": false,
  "tag": "",
  "blurb": "Le Tempest 900 walkaround, bi-motorisation Yamaha.",
  "gallery": [
   "assets/images/boats/o_capelli900/00.jpg",
   "assets/images/boats/o_capelli900/01.jpg",
   "assets/images/boats/o_capelli900/02.jpg",
   "assets/images/boats/o_capelli900/03.jpg",
   "assets/images/boats/o_capelli900/04.jpg"
  ],
  "specsheet": {
   "Longueur": "9m30",
   "Largeur": "3m21",
   "Poids": "1900 Kg",
   "Puissance max": "2 x 250",
   "Capacité": "16 pax",
   "Carburant": "400 Lt",
   "Eau": "70 Lt"
  }
 },
 "o_mako293": {
  "id": "o_mako293",
  "name": "Mako 293",
  "kind": "acheter",
  "cat": "occasion",
  "color": "",
  "length": 9.4,
  "cap": null,
  "power": "2 x 225 CV",
  "engine": "Honda",
  "price": 45000,
  "sold": false,
  "tag": "",
  "blurb": "Center console américain, idéal grande pêche et famille.",
  "gallery": [
   "assets/images/boats/o_mako293/00.jpg",
   "assets/images/boats/o_mako293/01.jpg",
   "assets/images/boats/o_mako293/02.jpg",
   "assets/images/boats/o_mako293/03.jpg",
   "assets/images/boats/o_mako293/04.jpg"
  ],
  "specsheet": {
   "Longueur": "9m40",
   "Largeur": "2m90",
   "Poids": "2270 Kg",
   "Puissance max": "450",
   "Capacité": "10 Pax.",
   "Carburant": "900 Lt",
   "Eau": "150 Lt",
   "Coque": "polyester"
  }
 },
 "o_cigarette35": {
  "id": "o_cigarette35",
  "name": "Cigarette Cafe Racer 35 – Refit 2025",
  "kind": "acheter",
  "cat": "occasion",
  "color": "",
  "length": 11.6,
  "cap": null,
  "power": "2 x 300 CV",
  "engine": "Suzuki",
  "price": 85000,
  "sold": false,
  "tag": "Refit 2025",
  "blurb": "La légende Cigarette, café racer refait à neuf — pièce rare.",
  "gallery": [
   "assets/images/boats/o_cigarette35/00.jpg",
   "assets/images/boats/o_cigarette35/01.jpg",
   "assets/images/boats/o_cigarette35/02.jpg",
   "assets/images/boats/o_cigarette35/03.jpg",
   "assets/images/boats/o_cigarette35/04.jpg"
  ],
  "specsheet": {
   "Longueur": "11.60",
   "Largeur": "2.5",
   "Poids": "3000 Kg",
   "Puissance max": "600",
   "Capacité": "8 pax",
   "Carburant": "600 Lt",
   "Eau": "100 Lt"
  }
 },
 "o_guycouach": {
  "id": "o_guycouach",
  "name": "Guy Couach 1602",
  "kind": "acheter",
  "cat": "occasion",
  "color": "",
  "length": 17.0,
  "cap": null,
  "power": "2 x 680 CV",
  "engine": "MAN",
  "price": 120000,
  "sold": true,
  "tag": "Refit 2023",
  "blurb": "Vedette de 17 m entièrement refaite en 2023 — désormais vendue.",
  "gallery": [
   "assets/images/boats/o_guycouach/00.jpg",
   "assets/images/boats/o_guycouach/01.jpg",
   "assets/images/boats/o_guycouach/02.jpg",
   "assets/images/boats/o_guycouach/03.jpg",
   "assets/images/boats/o_guycouach/04.jpg"
  ],
  "specsheet": {
   "Longueur": "17m00",
   "Largeur": "4m71",
   "Puissance max": "1360",
   "Carburant": "3500 Lt",
   "Eau": "1000 Lt",
   "Coque": "polyester/kevlar"
  }
 },
 "o_rodman56": {
  "id": "o_rodman56",
  "name": "Rodman 56",
  "kind": "acheter",
  "cat": "occasion",
  "color": "",
  "length": 17.36,
  "cap": null,
  "power": "2 x 750 CV",
  "engine": "Volvo Penta",
  "price": 315000,
  "sold": false,
  "tag": "",
  "blurb": "Un flybridge de 17 m, volumes de croisière généreux.",
  "gallery": [
   "assets/images/boats/o_rodman56/00.jpg",
   "assets/images/boats/o_rodman56/01.jpg",
   "assets/images/boats/o_rodman56/02.jpg",
   "assets/images/boats/o_rodman56/03.jpg",
   "assets/images/boats/o_rodman56/04.jpg"
  ],
  "specsheet": {
   "Longueur": "17m36",
   "Largeur": "4m90",
   "Puissance max": "1500",
   "Carburant": "2800 Lt",
   "Eau": "700 Lt",
   "Coque": "Polyester"
  }
 }
};
